// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./reset.css";
import "../styles/carouselBase.css";
import ReactQueryProviders from "@/api/ReactQueryProvider";
import "../styles/layout.module.scss";
import AppHeader from "./components/AppHeader";
import "../styles/globals.css";
import AppFooter from "./components/AppFooter";

export const basicFont = localFont({
  src: [
    {
      path: "./fonts/KimjungchulGothic-Light.ttf",
      weight: "300", // 400과 동일
      style: "normal",
    },
    {
      path: "./fonts/KimjungchulGothic-Regular.ttf",
      weight: "400", // 400과 동일
      style: "normal",
    },
    {
      path: "./fonts/KimjungchulGothic-Bold.ttf",
      weight: "700", // 700과 동일
      style: "normal",
    },
  ],
});

// export const metadata: Metadata = {
//   title: "minus-blog",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${basicFont.className}`}>
        <AppHeader />
        <ReactQueryProviders>
          <div className="wrapper">{children}</div>
        </ReactQueryProviders>
        <AppFooter />
        <div id="modal-root" />
        <div id="image-viewer-root" />
      </body>
    </html>
  );
}
