name: Deploy to S3 and CloudFront on Develop Push

on:
  push:
    branches:
      - develop # develop 브랜치에 push 발생 시 실행

jobs:
  build:
    name: install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # pnpm 설치
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      # .env에 있던 환경변수들을 등록해주는 단계
      - name: .env setting
        run: |
          echo "VITE_SUPABASE_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }}" >> .env
          echo "VITE_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env

      # Node.js 환경 설정 (pnpm을 사용하려면 필수)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm" # pnpm 캐싱 활성화 (속도 개선)

      # 패키지 설치
      - name: Install dependencies
        run: pnpm install

      # 빌드 실행
      - name: Build project
        run: pnpm build
      # 5. AWS S3에 업로드
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            dist s3://minus-cms \
            --delete

      # CloudFront 캐시 무효화
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: "/*"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          DISTRIBUTION: ${{ secrets.CLOUD_FRONT_DISTRIBUTION_ID }}

      # 6. 배포 완료 메시지 출력
      - name: Deployment complete
        run: echo "🚀 Deploy to S3 completed!"
